### ISSUE TITLE
[Feature request] GNOME 45 support

### ISSUE THREAD

**Issue by D3vil0p3r** [stuarthayhurst/remove-app-menu-extension#2]
Hello @stuarthayhurst
Will the extension support GNOME 45 that will be released in the third week of September?

**Comment by stuarthayhurst** [comment]
The app menu was removed in GNOME 45, so the extension won't be updated for GNOME 45. If they add some version of it back in later GNOME versions, I'll update the extension, but GNOME 45 support won't happen.
